import os
import shutil
import subprocess
import sys

# --- CONFIGURATION ---
APP_NAME = "CodeBase"
# Ideally read this from constants.py
VERSION = "6.1" 
PUBLISHER = "Your Name"
URL = "https://yourwebsite.com"
EXE_NAME = "CodeBase.exe"

# Paths
ASSETS_DIR = "assets"
DIST_DIR = "dist"
ICON_PATH = os.path.join(ASSETS_DIR, "icon.ico")

# Inno Setup Compiler Path (Standard location)
# You might need to add ISCC to your system PATH or adjust this string
ISCC_PATH = r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe"

def run_command(command):
    print(f"Running: {' '.join(command)}")
    try:
        subprocess.check_call(command)
    except subprocess.CalledProcessError as e:
        print(f"Error command failed: {e}")
        sys.exit(1)

def clean():
    print("Cleaning previous builds...")
    if os.path.exists(DIST_DIR): shutil.rmtree(DIST_DIR)
    if os.path.exists("build"): shutil.rmtree("build")
    if os.path.exists(f"{APP_NAME}.spec"): os.remove(f"{APP_NAME}.spec")
    if os.path.exists("setup_script.iss"): os.remove("setup_script.iss")

def build_binary():
    print("Compiling Python to Binary with PyInstaller...")
    
    if not os.path.exists(ICON_PATH):
        print(f"Error: Icon not found at {ICON_PATH}")
        sys.exit(1)

    cmd = [
        "pyinstaller",
        "--noconsole",
        "--onefile",
        "--name", APP_NAME,
        "--icon", ICON_PATH,
        # Windows uses ; for path separation in add-data
        "--add-data", f"codebase-icon.svg;.", 
        "main.py"
    ]
    run_command(cmd)

def generate_inno_script():
    print("Generating Inno Setup script...")
    
    # We generate this dynamically to keep Version synced
    iss_content = f"""
[Setup]
AppName={APP_NAME}
AppVersion={VERSION}
AppPublisher={PUBLISHER}
AppPublisherURL={URL}
DefaultDirName={{autopf}}\\{APP_NAME}
DefaultGroupName={APP_NAME}
; Save the installer in the dist folder
OutputDir={DIST_DIR}
OutputBaseFilename={APP_NAME}_Setup_v{VERSION}_x64
Compression=lzma2
SolidCompression=yes
ArchitecturesInstallIn64BitMode=x64
SetupIconFile={ICON_PATH}
UninstallDisplayIcon={{app}}\\{EXE_NAME}

[Tasks]
Name: "desktopicon"; Description: "{{cm:CreateDesktopIcon}}"; GroupDescription: "{{cm:AdditionalIcons}}"

[Files]
; The EXE generated by PyInstaller
Source: "{DIST_DIR}\\{EXE_NAME}"; DestDir: "{{app}}"; Flags: ignoreversion

[Icons]
Name: "{{group}}\\{APP_NAME}"; Filename: "{{app}}\\{EXE_NAME}}"
Name: "{{autodesktop}}\\{APP_NAME}"; Filename: "{{app}}\\{EXE_NAME}}"; Tasks: desktopicon

[Run]
Filename: "{{app}}\\{EXE_NAME}"; Description: "{{cm:LaunchProgram,{APP_NAME}}}"; Flags: nowait postinstall skipifsilent
"""
    with open("setup_script.iss", "w") as f:
        f.write(iss_content)

def build_installer():
    print("Compiling Installer with Inno Setup...")
    
    if not os.path.exists(ISCC_PATH):
        print(f"Error: Inno Setup Compiler not found at {ISCC_PATH}")
        print("Please install Inno Setup: https://jrsoftware.org/isdl.php")
        sys.exit(1)

    cmd = [ISCC_PATH, "setup_script.iss"]
    run_command(cmd)
    
    print(f"\nSUCCESS! Installer generated in {DIST_DIR}")

if __name__ == "__main__":
    if os.name != 'nt':
        print("Error: This script must be run on Windows.")
        sys.exit(1)
        
    clean()
    build_binary()
    generate_inno_script()
    build_installer()

